- ios/Nami.m
- ios/NamiPaywallManagerProxy.m
- ios/RNNami.xcodeproj/project.pbxproj
- package.json
Moved Nami bridging into its own class.
> Added new bridging for Nami class.

- examples/Analytics/package.json
- examples/Basic/containers/AboutScreen.js
- examples/Basic/package.json
- examples/BasicLinkedPaywall/components/LinkedPaywall/LinkedPaywall.js
- examples/BasicLinkedPaywall/package.json
- adjust dependencies
- add purchase success notification to BasicLinkedPaywall
> demo app updates

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiAnalyticsEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- examples/Analytics/package.json
- examples/Basic/package.json
- examples/BasicLinkedPaywall/package.json
- ios/Nami.m
- ios/Podfile
- package.json
- react-native-nami-sdk.podspec
- integrate latest iOS and Android SDKs
- add key-values for linked paywalls on Android
- internal improvements in to Nami API calls
- improved sign-in / sign-in behavior related to entitlements
> v0.1.42 release

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiEntitlementManagerBridgeModule.kt
- examples/Analytics/package.json
- examples/Basic/package.json
- examples/BasicLinkedPaywall/package.json
- ios/NamiEmitter.m
- ios/Podfile
- package.json
- react-native-nami-sdk.podspec
> update to latest android and ios SDKs

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiEntitlementManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- examples/BasicLinkedPaywall/android/app/build.gradle
- examples/BasicLinkedPaywall/android/app/src/main/AndroidManifest.xml
- examples/BasicLinkedPaywall/android/app/src/main/java/com/namiml/demo/linked/MainActivity.java
- examples/BasicLinkedPaywall/android/app/src/main/java/com/namiml/demo/linked/MainApplication.java
- examples/BasicLinkedPaywall/android/build.gradle
- examples/BasicLinkedPaywall/android/gradle/wrapper/gradle-wrapper.properties
- examples/BasicLinkedPaywall/containers/HomeScreen.js
Also
- cleaned up some `build.gradle` code
- Bump up targetSdk for android to `30` for both `linked example` and `bridge`
- Moved to `Kotlin 1.4.0`
> Update linked demo android app's package + Bump up Android SDK to 0.3.1

- .gitignore
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiBridgePackage.java
- android/src/main/java/com/nami/reactlibrary/NamiCustomerManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiEntitlementManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiMLManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- examples/Basic/android/build.gradle
- ios/NamiAnalyticsEmitter.m
- ios/NamiCustomerManager.m
- ios/NamiEmitter.m
- ios/Podfile
- ios/RNNami.xcodeproj/project.pbxproj
- package.json
- react-native-nami-sdk.podspec
Native SDKs
- Updated to Android pre-release SDK 0.4.0
- Updated to Apple SDK 2.3.1
Bridge Updates
- Added NamiCustomerManagerBridge.currentCustomerJourneyState
- Added support for blocking paywalls
- Added EntitlementsChanged event
> v0.2.0 bridge release

- examples/Analytics/ios/Podfile
- examples/Analytics/package.json
- examples/Basic/ios/Podfile
- examples/Basic/package.json
- examples/BasicLinkedPaywall/ios/Podfile
- examples/BasicLinkedPaywall/package.json
- Update to React Native 0.63.3 for all sample apps
- Update all other dependencies to latest
> Update sample app dependencies

- ios/Nami.m
- ios/NamiBridgeUtil.h
- ios/NamiBridgeUtil.m
- ios/NamiEmitter.m
- ios/NamiPaywallManagerBridge.m
Updates for iOS SDK 2.4.0 including paywall styling changes and a few API tweaks.
> Nami iOS 2.4.0 feature updates (Paywall styling)

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/nami/reactlibrary/Constants.kt
- android/src/main/java/com/nami/reactlibrary/NamiAnalyticsEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiCustomerManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiEntitlementManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiMLManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPurchaseManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- examples/Basic/android/build.gradle
- examples/Basic/android/gradle/wrapper/gradle-wrapper.properties
- examples/BasicLinkedPaywall/android/build.gradle
- examples/BasicLinkedPaywall/android/gradle/wrapper/gradle-wrapper.properties
NOTE that since SDK is not released, if you want to run this branch, you would have to locally publish Android SDK after changing the version number
> Update android bridge to be compatible with Android SDK 0.5.0

- examples/Analytics/ios/Analytics.xcodeproj/project.pbxproj
- examples/Analytics/ios/Analytics.xcodeproj/xcshareddata/xcschemes/Analytics.xcscheme
- examples/Analytics/ios/TestProducts.storekit
- examples/Basic/ios/Basic.xcodeproj/project.pbxproj
- examples/Basic/ios/Basic.xcodeproj/xcshareddata/xcschemes/Basic.xcscheme
- examples/Basic/ios/TestProducts.storekit
- examples/BasicLinkedPaywall/ios/BasicLinkedPaywall.xcodeproj/project.pbxproj
- examples/BasicLinkedPaywall/ios/BasicLinkedPaywall.xcodeproj/xcshareddata/xcschemes/BasicLinkedPaywall.xcscheme
- examples/BasicLinkedPaywall/ios/TestProducts.storekit
- ios/NamiBridgeUtil.h
- ios/NamiBridgeUtil.m
Added paywall style data to paywall payloads.
Also added StoreKit configuration to example IOS projects.
> Style Data Added

- android/src/main/java/com/nami/reactlibrary/NamiPurchaseManagerBridge.kt
Return an unwrapped boolean in result from BuySKU.
> Android buy SKU bool fix

- examples/Basic/android/app/build.gradle
- examples/Basic/android/app/src/main/AndroidManifest.xml
- examples/Basic/android/app/src/main/java/com/namiml/demo/basic/MainActivity.java
- examples/Basic/android/app/src/main/java/com/namiml/demo/basic/MainApplication.java
To test real purchase, go to `App.js` in the `basic` app and replace `configDict` code with following and run the app
```
let configDict = {
'appPlatformID-apple': '002e2c49-7f66-4d22-a05c-1dc9f2b7f2af',
'appPlatformID-google': 'bc22f384-20ea-431c-96ce-15b5ac6ea807',
logLevel: 'DEBUG',
developmentMode: false,
bypassStore: false,
};
```
> Change package for basic app to be in sync with published app package

- README.md
- examples/Analytics/package.json
- examples/Basic/android/app/build.gradle
- examples/Basic/android/app/src/main/AndroidManifest.xml
- examples/Basic/android/app/src/main/java/com/namiml/demo/basic/MainActivity.java
- examples/Basic/android/app/src/main/java/com/namiml/demo/basic/MainApplication.java
- examples/Basic/package.json
- examples/BasicLinkedPaywall/package.json
- package.json
- update android basic example app to work with app on play store
- update docs
> misc updates

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiAnalyticsEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiBridgePackage.java
- android/src/main/java/com/nami/reactlibrary/NamiCustomerManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiEmitter.kt
- android/src/main/java/com/nami/reactlibrary/NamiEntitlementManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiMLManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPurchaseManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- Add support for `formatted_skus` in Paywall
- Add support for `use_bottom_overlay` in Paywall
- Add support for `raisePaywall` by developerPaywallId
- Refactor all methods in `NamiUtil` to Kotlin extension methods on particular objects
- Fix issues related to NamiPaywall map and PeriodUnit
> Update Android SDK to 1.0.0

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- examples/Analytics/containers/HomeScreen.js
- examples/Analytics/package.json
- examples/Basic/containers/HomeScreen.js
- examples/Basic/package.json
- examples/BasicLinkedPaywall/containers/HomeScreen.js
- examples/BasicLinkedPaywall/package.json
- ios/NamiBridgeUtil.m
- ios/NamiEmitter.m
- ios/NamiPaywallManagerBridge.m
- ios/Podfile
- package.json
- react-native-nami-sdk.podspec
- add support for smart text
- integrate android sdk v1.2.1
- integrate ios sdk v2.7.0
> smart text support and sdk updates

- examples/Analytics/components/Header/Header.js
- examples/Analytics/containers/HomeScreen.js
- examples/Basic/components/Header/Header.js
- examples/Basic/containers/HomeScreen.js
- examples/BasicLinkedPaywall/components/Header/Header.js
- examples/BasicLinkedPaywall/containers/HomeScreen.js
Updates branding colors in Analytics, Basic, and BasicLinked sample apps
> update brand colors in sample apps

- examples/Basic/package.json
> Further CI/CD exploration

- .github/workflows/app_stg.yaml
- ios/Podfile
> Update Apple SDK

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- ios/Nami.m
- package.json
- react-native-nami-sdk.podspec
- Bridge version bump
- Apple SDK bump to 3.0.14
- Android SDK bump to 3.0.12
> Bump native SDK versions

- .github/workflows/app_prod.yaml
- .github/workflows/app_stg.yaml
- android/build.gradle
- examples/TestNamiTV/android/app/build.gradle
- examples/TestNamiTV/android/build.gradle
- package.json
- Bump Native Android dependency to 3.0.13
- CI Tweaks
> bump to 3.0.13 and ci

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- examples/TestNamiTV/android/app/build.gradle
- ios/Nami.m
- package.json
- also update TestNamiTV test app
> Bump minSdkVersion to 22

- src/NamiPaywallManager.js
- Fix reference to `NamiPaywallManager.hide`
> Fix hide reference

- examples/Basic/config/index.ts
- examples/Basic/containers/CampaignScreen.tsx
- examples/Basic/services/deeplinking.ts
- examples/TestNamiTV/config/index.ts
- examples/TestNamiTV/containers/CampaignScreen.tsx
- examples/TestNamiTV/services/deeplinking.ts
- src/NamiCampaignManager.d.ts
- src/NamiCampaignManager.js
- Fix actionCallback order to resolve type warning
- Adjust sample apps
> Bugfix: actionCallback order resolution

- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- examples/Basic/containers/CampaignScreen.tsx
- ios/Nami.m
- ios/NamiPaywallManagerBridge.m
- ios/NamiPaywallManagerBridge.swift
- react-native-nami-sdk.podspec
- src/NamiPaywallManager.d.ts
- src/NamiPaywallManager.js
- Apple: Add `NamiPaywallManager.isHidden` for advanced use case where Nami Window is in use.
- Supporting dependency update: Apple SDK v3.0.25
> Enhancement: add `NamiPaywallManager.isHidden`

- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
> Android isHidden 

- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- examples/Basic/containers/CampaignScreen.tsx
- ios/Nami.m
- ios/NamiPaywallManagerBridge.m
- ios/NamiPaywallManagerBridge.swift
- package.json
- src/NamiPaywallManager.d.ts
- src/NamiPaywallManager.js
- Add `NamiPaywallManager.registerRestoreHandler`
- Update sample project
- Version bump the bridge
> Ehhancement: Add registerRestoreHandler

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiCampaignManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiUtil.kt
- ios/Nami.m
- package.json
- react-native-nami-sdk.podspec
- Update Android dependency to 3.1.0, with supporting change in the bridge
- Update Apple dependency to 3.1.2
> Update native dependencies

- examples/Basic/containers/CampaignScreen.tsx
Fix bug where frigate templates raise without any product groups
> Change productGroups to empty object instead of empty array

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- examples/Basic/android/app/build.gradle
- examples/TestNamiTV/android/app/build.gradle
- ios/Nami.m
- package.json
Update Android dependency to 3.1.10-beta.04
> 3.0.35-beta.1

- react-native-nami-sdk.podspec
- Update Apple dependency to 3.1.14
> Update Apple native dependency to 3.1.14

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- examples/Basic/android/app/build.gradle
- examples/TestNamiTV/android/app/build.gradle
- ios/Nami.m
- react-native-nami-sdk.podspec
- src/Nami.d.ts
- src/types.ts
- https://github.com/namiml/react-native-nami-sdk/wiki/Nami-SDK-Early-Access-Releases#v3119-beta1-nov-8-2023
> 3.1.19-beta.1

- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- examples/Basic/App.tsx
- examples/Basic/android/app/build.gradle
- examples/Basic/config/index.ts
- examples/Basic/containers/CampaignScreen.tsx
- examples/TestNamiTV/android/app/build.gradle
- ios/Nami.m
- package.json
- Android SDK v3.1.21-beta.03 [Release Notes](https://github.com/namiml/nami-android/wiki/Nami-SDK-Early-Access-Releases#v3121-beta03-dec-4-2023)
> 3.1.21-beta.5

- examples/Basic/containers/CampaignScreen.tsx
- examples/Basic/e2e/ios/main.test.js
Testing issue with detox tests
> fix(detox-tests): Timeout tests on iOS.

- examples/Basic/index.js
- examples/TestNamiTV/index.js
- src/Nami.d.ts
- src/Nami.ts
- Update Nami.Configure to `promise-based` instead of `callback`
- Update examples
> NC-4887: Update Nami.Configure to promise based

- .github/workflows/app_prod.yaml
- .github/workflows/app_stg.yaml
- examples/Basic/containers/CampaignScreen.tsx
- examples/Basic/index.js
- ios/Nami.m
- ios/NamiPaywallManagerBridge.swift
- src/Nami.d.ts
- src/Nami.ts
- Code examples for new api interfaces introduced in 3.2.0
- Update CI runner to macos-13 and Xcode 15.0.1
> Chore: update example app and CI Xcode version

- android/src/main/java/com/nami/reactlibrary/NamiCampaignManagerBridge.kt
- ios/NamiCampaignManagerBridge.swift
- package.json
Populate the paywall event passed from the native bridge to React Native with a sku when available
> paywall event sku bugfix

- examples/Basic/ios/Basic/Info.plist
- add support for all orientations for iPad in sample app
> Sample app: add all orientations for ipad

- .github/workflows/app_prod.yaml
- .github/workflows/app_stg.yaml
- android/build.gradle
- android/src/main/java/com/nami/reactlibrary/NamiBridgeModule.kt
- android/src/main/java/com/nami/reactlibrary/NamiCampaignManagerBridge.kt
- android/src/main/java/com/nami/reactlibrary/NamiPaywallManagerBridgeModule.kt
- examples/Basic/index.js
- examples/TestNamiTV/index.js
- ios/Nami.m
- ios/NamiCampaignManagerBridge.swift
- package.json
- react-native-nami-sdk.podspec
- Amazon: Honor `allowOffers` flag in `NamiPaywallManager.setProductsDetails` 
- Android SDK v3.2.4-beta.01
- Apple SDK v3.2.4-beta.01
> 3.2.4-beta.1

- .github/workflows/app_prod.yaml
- .github/workflows/app_stg.yaml
- examples/TestNamiTV/package.json
- Update Xcode to 16.0.0 per Apple submission guidelines
- Update TestFlight release notes based upon PR title
- Pin react-native-reanimated version to fix tvOS build
> update to Xcode 16.0.0 and pin react-native-reanimated for tvOS build

- dist/src/version.d.ts
- examples/Basic/ios/Basic.xcodeproj/project.pbxproj
- examples/TestNamiTV/ios/Basic.xcodeproj/project.pbxproj
- src/version.ts
> Fix Xcode build script
